# image: docker:18-git

# services:
#   - name: docker:18.09-dind
image: maven:latest

stages:
  - build
  - test
  - deploy_test
  - deploy_prod

build:
  image: maven:latest
  stage: build
  tags:
    - ugrad
  script:
    - mvn compile
  artifacts:
    paths:
      - target
test:
  image: maven:latest
  stage: test
  tags:
    - ugrad
  script:
    - mvn clean verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml



deployProd:
  image: maven:latest
  stage: deploy_prod
  tags:
    - ugrad
  #  artifacts:
  #    paths:
  #      # Change this directory to the path that contains your built executable
  #      - target
  before_script:
    - echo "beforeScript"
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${DEPLOY_SSH_KEY_PROD}")

  script:
    - databaseFile="application.properties"
    - echo "PROD_URL= ${DB_PROD_URL}" > databaseFile
    - echo "PROD_USER= ${DB_PROD_USER}" >> databaseFile
    - echo "PROD_PASS= ${DB_PROD_PASS}" >> databaseFile
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip *
    - scp -r -o StrictHostKeyChecking=no ${databaseFile} "${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD}:${DEPLOY_DIR_PROD}/${databaseFile}"
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER_PROD}@${DEPLOY_HOST_PROD}:${DEPLOY_DIR_PROD}/${CI_COMMIT_SHORT_SHA}.zip"
  only:
    - release

deployTest:
  image: maven:latest
  stage: deploy_test
  tags:
    - ugrad
  artifacts:
    paths:
      - target

  before_script:
    - echo "beforeScript"
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo "${DEPLOY_SSH_KEY}")

  script:
    - database="application.properties"
    - echo "TEST_URL= ${DB_TEST_URL}" > $database
    - echo "TEST_USER= ${DB_TEST_USER}" >> $database
    - echo "TEST_PASS= ${DB_TEST_PASS}" >> $database
    - zip -r ${CI_COMMIT_SHORT_SHA}.zip *
    - scp -r -o StrictHostKeyChecking=no ${database} "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${database}"
    - scp -r -o StrictHostKeyChecking=no ${CI_COMMIT_SHORT_SHA}.zip "${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIR}/${CI_COMMIT_SHORT_SHA}.zip"
  only:
    - develop